services:
  database:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: oracle-23ai
    env_file:
      - .env
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - '1521:1521'
    profiles: ["prod", "otel"]
  
  app:
    image: parksofprague:latest
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - '8080:8080'
    command: ["--hostname", "0.0.0.0", "--port", "8080"]
    profiles: ["prod"]
      
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml 
    profiles: ["prod", "otel"]
  
  otel-collector:
      image: otel/opentelemetry-collector-contrib
      depends_on:
        - jaeger
      command: ["--config=/etc/otel-collector-config.yml"]
      ports:
        - "7070:7070"
        - "4317:4317"
      volumes:
        - "./config/otel-collector-config.yml:/etc/otel-collector-config.yml"
      profiles: ["prod", "otel"]
    
  prometheus:
    image: prom/prometheus
    depends_on:
      - otel-collector
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    profiles: ["prod", "otel"]

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "4317"
      - "16686:16686" # This is Jaeger's Web UI, visualizing recorded traces
    volumes:
      - "./data/jaeger:/badger"
    environment:
      - SPAN_STORAGE_TYPE=badger # Use local storage
      - BADGER_EPHEMERAL=false  # Don't use ephemeral storage
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    profiles: ["prod", "otel"]
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - jaeger
    volumes:
      - ./config/grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
    profiles: ["prod", "otel"]

volumes:
  oracle_data:
    driver: local
